name: Auto review tutorial description

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  auto_review:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{github.event.number}}

    steps:
      - name: Checkout playbooks
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorials

      - name: Install node environment
        uses: actions/setup-node@v2-beta

      - name: npm install
        run: npm install

      - name: Check tutorial descriptions
        id: check_tutorial_description
        run: node autoReviewPullRequest.js

      - name: Get message
        id: get_message
        run: |
          cat message.txt
          message=`cat message.txt`
          echo "1"
          echo ${message}
          echo "2"
          echo "::set-output name=message::$message"

      - name: Test
        run: echo "Test ${{ steps.get_message.outputs.message }}"

      - name: Request changes
        if:  ${{ steps.get_message.outputs.message != '' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: REQUEST_CHANGES
          body: ${{ env.REQUEST_CHANGE_MESSAGE }}

