name: Auto review tutorial description

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  auto_review:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{github.event.number}}

    steps:
      - name: Checkout playbooks
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorials

      - name: Install node environment
        uses: actions/setup-node@v2-beta

      - name: npm install
        run: npm install

      - name: Check tutorial descriptions
        run: node repo/autoReviewPullRequest.js

      - name: Echo
        run: echo "$REQUEST_CHANGE_MESSAGE"

      - name: Request changes
        if:  ${{ env.REQUEST_CHANGE_MESSAGE != '' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: REQUEST_CHANGES
          body: ${{ env.REQUEST_CHANGE_MESSAGE }}

