name: Check PR Katacoda Syntax

on:
  pull_request_target:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tutorial-compiler
        uses: actions/checkout@v2
        with:
          ref: feature/syntaxChecking
          repository: MarcelDiessner/tutorial-compiler
      
      - name: Checkout playbooks
        uses: actions/checkout@v2
        with:
          ref: feature/syntaxChecking
          repository: MarcelDiessner/tutorials
          path: playbooks
      
      - uses: actions/setup-node@v2-beta
      
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run buildRun.sh --user ${{ github.actor }} --branch ${{ github.event.pull_request_target.head.ref }} --checkSyntax
        run: sh buildRun.sh --user ${{ github.actor }} --branch ${{ github.event.pull_request_target.head.ref }} --checkSyntax -e katacoda
      
      - name: Check error file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./build/errors/syntaxErrors.md"
          
      - name: Get message
        id: get_message
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          message=`cat ./build/errors/syntaxErrors.md`
          echo "${message}"
          (echo "MESSAGE=$(echo "${message}")") >> $GITHUB_ENV

      - name: Comment Syntax Errors
        if:  ${{ env.MESSAGE != '' }}
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ${{ env.MESSAGE }}

      - name: Request changes
        if:  ${{ env.MESSAGE != '' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: REQUEST_CHANGES
          body: ${{ env.MESSAGE }}